BASE_PROFILES = {
    "홍길동": {
        "gender": 1, "age": 42, "age_group": 40, "education": 5,
        "employment_type": 3, "employment_status": 1, "occupation": 7,
        "industry": 3, "company_size": 5, "work_hours": 45,
        "shift_work": 2, "night_work": 2, "working_years": 8,
        "safety_training": 2, "training_participation": 1,
        "physical_risk1": 4, "physical_risk2": 4, "physical_risk3": 4,
        "physical_risk4": 5, "physical_risk5": 4, "physical_risk6": 5,
        "physical_risk7": 4, "physical_risk8": 5, "physical_risk9": 5,
        "ergonomic_risk1": 4, "ergonomic_risk2": 4, "ergonomic_risk3": 4,
        "ergonomic_risk4": 3, "ergonomic_risk5": 5, "ergonomic_risk6": 4,
        "psychosocial_risk1": 4, "psychosocial_risk2": 4, "psychosocial_risk3": 4,
        "health_condition": 3, "work_related_disease": 2,
        "injury_absence_days": 2, "illness_absence_days": 1,
        "presenteeism": 2, "sleep_quality1": 4, "sleep_quality2": 4,
        "sleep_quality3": 4, "well_being": 3
    },
    "이철수": {
        "gender": 1, "age": 35, "age_group": 30, "education": 6,
        "employment_type": 3, "employment_status": 1, "occupation": 13,
        "industry": 10, "company_size": 10, "work_hours": 40,
        "shift_work": 0, "night_work": 0, "working_years": 10,
        "safety_training": 1, "training_participation": 1,
        "physical_risk1": 7, "physical_risk2": 7, "physical_risk3": 7,
        "physical_risk4": 6, "physical_risk5": 7, "physical_risk6": 7,
        "physical_risk7": 7, "physical_risk8": 6, "physical_risk9": 7,
        "ergonomic_risk1": 6, "ergonomic_risk2": 7, "ergonomic_risk3": 6,
        "ergonomic_risk4": 6, "ergonomic_risk5": 6, "ergonomic_risk6": 7,
        "psychosocial_risk1": 6, "psychosocial_risk2": 6, "psychosocial_risk3": 7,
        "health_condition": 1, "work_related_disease": 2,
        "injury_absence_days": 0, "illness_absence_days": 0,
        "presenteeism": 2, "sleep_quality1": 5, "sleep_quality2": 5,
        "sleep_quality3": 5, "well_being": 2
    },
    "박영희": {
        "gender": 2, "age": 55, "age_group": 50, "education": 3,
        "employment_type": 1, "employment_status": 2, "occupation": 9,
        "industry": 9, "company_size": 1, "work_hours": 60,
        "shift_work": 3, "night_work": 4, "working_years": 2,
        "safety_training": 4, "training_participation": 2,
        "physical_risk1": 2, "physical_risk2": 2, "physical_risk3": 2,
        "physical_risk4": 3, "physical_risk5": 2, "physical_risk6": 3,
        "physical_risk7": 2, "physical_risk8": 3, "physical_risk9": 2,
        "ergonomic_risk1": 2, "ergonomic_risk2": 2, "ergonomic_risk3": 3,
        "ergonomic_risk4": 2, "ergonomic_risk5": 4, "ergonomic_risk6": 2,
        "psychosocial_risk1": 2, "psychosocial_risk2": 2, "psychosocial_risk3": 2,
        "health_condition": 4, "work_related_disease": 1,
        "injury_absence_days": 5, "illness_absence_days": 6,
        "presenteeism": 1, "sleep_quality1": 2, "sleep_quality2": 2,
        "sleep_quality3": 2, "well_being": 6
    },
    "김철수":{
        "gender": 1,
        "age": 70,
        "age_group": 60,
        "education": 3.0,
        "employment_type": 1.0,
        "employment_status": 1.0,
        "occupation": 8,
        "industry": 8,
        "company_size": 2.0,
        "work_hours": 50.0,
        "shift_work": 2.0,
        "night_work": 10.0,
        "physical_risk1": 7.0,
        "physical_risk2": 7.0,
        "physical_risk3": 7.0,
        "physical_risk4": 7.0,
        "physical_risk5": 7.0,
        "physical_risk6": 7.0,
        "physical_risk7": 7.0,
        "physical_risk": 7.0,
        "physical_risk.1": 7.0,
        "ergonomic_risk1": 7.0,
        "ergonomic_risk2": 7.0,
        "ergonomic_risk3": 7.0,
        "ergonomic_risk4": 7.0,
        "ergonomic_risk5": 1.0,
        "ergonomic_risk6": 1.0,
        "psychosocial_risk1": 1.0,
        "psychosocial_risk2": 7.0,
        "psychosocial_risk3": 7.0,
        "health_condition": 3.0,
        "work_related_disease": 1.0,
        "injury_absence_days": 0.0,
        "illness_absence_days": 2.0,
        "presenteeism": 2.0,
        "sleep_quality1": 4.0,
        "sleep_quality2": 4.0,
        "sleep_quality3": 4.0,
        "well_being": 3.0,
        "working_years": 35.0,
        "safety_training": 1.0,
        "training_participation": 2.0
    }
}